import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from './models/User.js';
import Profile from './models/Profile.js';
import Puzzle from './models/Puzzle.js';
import StoreItem from './models/StoreItem.js';
import Leaderboard from './models/Leaderboard.js';
import Achievement from './models/Achievement.js';
import DailyReward from './models/DailyReward.js';

dotenv.config();

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    await Promise.all([
      Puzzle.deleteMany({}),
      StoreItem.deleteMany({}),
      Leaderboard.deleteMany({}),
      Achievement.deleteMany({})
    ]);
    console.log('Cleared existing seed data');

    // Seed Puzzles - 75 total (15 per room, 5 levels x 3 per level)
    const puzzles = await Puzzle.insertMany([
      // ==================== FOYER (15 puzzles) ====================
      // --- Level 1 (Easy) ---
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'The Riddle Door', type: 'riddle', objectName: 'door', level: 1, difficulty: 'easy', description: 'The door has a carved face that speaks in riddles.', question: 'I have cities but no houses, forests but no trees, water but no fish. What am I?', answer: 'map', options: ['map', 'globe', 'painting', 'dream'], hint1: 'Think of something that represents places...', hint2: 'You might unfold me on a table to plan a trip.', hint3: 'A MAP shows cities, forests, and water but has none of them.', points: 100, order: 1, rewards: { coins: 30, xp: 20, item: 'old-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Clock Riddle', type: 'riddle', objectName: 'clock', level: 1, difficulty: 'easy', description: 'A message carved below the clock face.', question: 'What has hands but cannot clap?', answer: 'clock', options: ['clock', 'mannequin', 'statue', 'gloves'], hint1: 'It tells you something important every day...', hint2: 'You look at it to know when to eat.', hint3: 'A CLOCK has hands but cannot clap.', points: 80, order: 2, rewards: { coins: 25, xp: 15 } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Number Frame', type: 'math', objectName: 'painting', level: 1, difficulty: 'easy', description: 'Numbers painted into the landscape.', question: 'What is 15 + 27?', answer: '42', options: ['38', '42', '45', '52'], hint1: 'Add the ones digits first: 5 + 7 = 12.', hint2: 'Carry the 1. Then 1 + 2 + 1 = 4.', hint3: '15 + 27 = 42.', points: 60, order: 3, rewards: { coins: 20, xp: 10, item: 'painting-shard' } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Word Lock', type: 'word', objectName: 'door', level: 1, difficulty: 'easy', description: 'A padlock with letters instead of numbers.', question: 'Unscramble: P-O-E-N to form something you open.', answer: 'open', options: [], hint1: 'It\'s what you do with a door...', hint2: 'Rearrange the 4 letters.', hint3: 'OPEN - just rearrange P-O-E-N.', points: 80, order: 4, rewards: { coins: 25, xp: 15, item: 'foyer-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Mirror Count', type: 'observation', objectName: 'clock', level: 1, difficulty: 'easy', description: 'The clock reflects oddly in the mirror.', question: 'If a clock shows 3:00, how many degrees between the hands?', answer: '90', options: ['60', '90', '120', '180'], hint1: 'A full circle is 360 degrees, divided into 12 hours.', hint2: 'Each hour mark is 30 degrees apart.', hint3: '3 hours x 30 degrees = 90 degrees.', points: 90, order: 5, rewards: { coins: 30, xp: 20 } },

      // --- Level 2-3 (Medium) ---
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'The Secret Keeper', type: 'logic', objectName: 'clock', level: 2, difficulty: 'medium', description: 'The clock whispers a logic puzzle.', question: 'If you have me, you want to share me. If you share me, you don\'t have me. What am I?', answer: 'secret', options: [], hint1: 'Think of something valuable that loses value when shared...', hint2: 'People whisper these to trusted friends.', hint3: 'A SECRET - once shared, it\'s no longer just yours.', points: 120, order: 6, rewards: { coins: 40, xp: 25 } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Portrait Math', type: 'math', objectName: 'painting', level: 2, difficulty: 'medium', description: 'Numbers hidden in the portrait brushstrokes.', question: 'I am an odd number. Take away one letter and I become even. What number am I?', answer: 'seven', options: ['seven', 'three', 'five', 'nine'], hint1: 'Think about the word, not just the number...', hint2: 'Remove the letter "s" from the word.', hint3: 'SEVEN without S = EVEN.', points: 100, order: 7, rewards: { coins: 35, xp: 20, item: 'portrait-clue' } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Letter Logic', type: 'word', objectName: 'door', level: 3, difficulty: 'medium', description: 'A coded message etched in the door frame.', question: 'What occurs once in a minute, twice in a moment, but never in a thousand years?', answer: 'm', options: [], hint1: 'Look at the letters in each word...', hint2: 'Count the letter M in each word.', hint3: 'The letter M appears once in "minute", twice in "moment", never in "a thousand years".', points: 140, order: 8, rewards: { coins: 45, xp: 30, item: 'door-cipher' } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Pattern Tiles', type: 'sequence', objectName: 'painting', level: 3, difficulty: 'medium', description: 'The painting\'s tiles follow a pattern.', question: 'What comes next: 2, 4, 8, 16, __?', answer: '32', options: ['24', '30', '32', '36'], hint1: 'Each number is double the previous.', hint2: 'Multiply by 2 each time.', hint3: '16 x 2 = 32.', points: 110, order: 9, rewards: { coins: 35, xp: 25 } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Riddle of Ages', type: 'riddle', objectName: 'clock', level: 2, difficulty: 'medium', description: 'An old riddle about time.', question: 'What goes up but never comes down?', answer: 'age', options: ['age', 'rocket', 'ball', 'smoke'], hint1: 'Everyone experiences this...', hint2: 'It only increases as time passes.', hint3: 'Your AGE goes up but never comes down.', points: 100, order: 10, rewards: { coins: 30, xp: 20 } },

      // --- Level 4-5 (Hard) ---
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Grandfather Cipher', type: 'cipher', objectName: 'clock', level: 4, difficulty: 'hard', description: 'The grandfather clock displays encoded symbols.', question: 'A=1, B=2... If DOOR = 4+15+15+18, what is the sum?', answer: '52', options: [], hint1: 'D=4, O=15, O=15, R=18.', hint2: 'Add them together.', hint3: '4+15+15+18 = 52.', points: 180, order: 11, rewards: { coins: 60, xp: 40, item: 'cipher-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'The Impossible Riddle', type: 'logic', objectName: 'painting', level: 5, difficulty: 'hard', description: 'A riddle that seems impossible at first glance.', question: 'A man is looking at a portrait. "Brothers and sisters I have none, but that man\'s father is my father\'s son." Who is in the portrait?', answer: 'son', options: ['himself', 'son', 'father', 'nephew'], hint1: '"My father\'s son" with no siblings = himself.', hint2: 'So "that man\'s father" = himself.', hint3: 'If he is that man\'s father, that man is his SON.', points: 250, order: 12, rewards: { coins: 80, xp: 60, item: 'portrait-secret' } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Number Sequence Master', type: 'sequence', objectName: 'door', level: 4, difficulty: 'hard', description: 'The door lock requires a sequence answer.', question: 'What comes next: 1, 1, 2, 3, 5, 8, __?', answer: '13', options: ['10', '11', '12', '13'], hint1: 'Each number is the sum of the two before it.', hint2: 'This is the famous Fibonacci sequence.', hint3: '5 + 8 = 13.', points: 200, order: 13, rewards: { coins: 70, xp: 50, item: 'golden-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'Binary Lock', type: 'cipher', objectName: 'door', level: 5, difficulty: 'hard', description: 'The door mechanism uses binary code.', question: 'What is the decimal value of binary 1010?', answer: '10', options: ['8', '10', '12', '16'], hint1: 'From right: 0, 1x2, 0, 1x8.', hint2: '8 + 0 + 2 + 0.', hint3: 'Binary 1010 = 8+2 = 10.', points: 220, order: 14, rewards: { coins: 75, xp: 55, item: 'binary-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'foyer', name: 'The Philosophers Stone', type: 'logic', objectName: 'painting', level: 5, difficulty: 'hard', description: 'An ancient philosophical puzzle.', question: 'If a statement says "This statement is false", is it true or false? Answer: paradox', answer: 'paradox', options: ['true', 'false', 'paradox', 'neither'], hint1: 'If it\'s true, then it must be false...', hint2: 'If it\'s false, then it must be true...', hint3: 'It\'s a PARADOX - it cannot be consistently true or false.', points: 280, order: 15, rewards: { coins: 90, xp: 70, item: 'philosophers-stone' } },

      // ==================== LIBRARY (15 puzzles) ====================
      // --- Level 1 (Easy) ---
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Musical Keys', type: 'riddle', objectName: 'bookshelf', level: 1, difficulty: 'easy', description: 'A music book lies open on the shelf.', question: 'What has many keys but can\'t open a single lock?', answer: 'piano', options: ['piano', 'keyboard', 'map', 'book'], hint1: 'Think of something musical...', hint2: 'It has 88 keys and makes beautiful sounds.', hint3: 'A PIANO has keys but opens no locks.', points: 100, order: 16, rewards: { coins: 30, xp: 20, item: 'torn-page' } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'World Traveler', type: 'observation', objectName: 'painting', level: 1, difficulty: 'easy', description: 'A painting of a world map.', question: 'What can travel around the world while staying in a corner?', answer: 'stamp', options: ['stamp', 'moon', 'internet', 'thought'], hint1: 'Think of something you put on mail...', hint2: 'It sits in the corner of an envelope.', hint3: 'A STAMP travels the world in corners of envelopes.', points: 90, order: 17, rewards: { coins: 25, xp: 15, item: 'magnifying-glass' } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Simple Addition', type: 'math', objectName: 'table', level: 1, difficulty: 'easy', description: 'Numbers scribbled on a bookmark.', question: 'What is 23 + 19?', answer: '42', options: ['38', '40', '42', '44'], hint1: '3 + 9 = 12, carry the 1.', hint2: '2 + 1 + 1 = 4.', hint3: '23 + 19 = 42.', points: 60, order: 18, rewards: { coins: 20, xp: 10 } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Bookworm Riddle', type: 'riddle', objectName: 'bookshelf', level: 1, difficulty: 'easy', description: 'A children\'s book with a riddle.', question: 'What has words but never speaks?', answer: 'book', options: ['book', 'sign', 'computer', 'letter'], hint1: 'You\'re surrounded by thousands of these...', hint2: 'You read them for knowledge and fun.', hint3: 'A BOOK has words but never speaks.', points: 80, order: 19, rewards: { coins: 25, xp: 15 } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Alphabet Order', type: 'word', objectName: 'table', level: 1, difficulty: 'easy', description: 'Letter tiles scattered on the table.', question: 'Which letter comes exactly in the middle of the alphabet?', answer: 'm', options: ['l', 'm', 'n', 'o'], hint1: 'The alphabet has 26 letters.', hint2: 'The middle of 26 is position 13.', hint3: 'M is the 13th letter - right in the middle.', points: 70, order: 20, rewards: { coins: 20, xp: 12 } },

      // --- Level 2-3 (Medium) ---
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Scholar\'s Word', type: 'word', objectName: 'table', level: 2, difficulty: 'medium', description: 'Scattered letters on the desk form a puzzle.', question: 'What 5-letter word becomes shorter when you add two letters to it?', answer: 'short', options: [], hint1: 'The answer describes length...', hint2: 'Add "er" to the end.', hint3: 'SHORT + ER = SHORTER.', points: 130, order: 21, rewards: { coins: 45, xp: 30, item: 'library-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Encyclopedia Logic', type: 'logic', objectName: 'bookshelf', level: 2, difficulty: 'medium', description: 'A logic puzzle from an old encyclopedia.', question: 'If all Bloops are Razzies, and all Razzies are Lazzies, are all Bloops definitely Lazzies?', answer: 'yes', options: ['yes', 'no', 'maybe', 'sometimes'], hint1: 'Think about nested categories...', hint2: 'If A is inside B, and B is inside C...', hint3: 'YES - Bloops are inside Razzies which are inside Lazzies.', points: 120, order: 22, rewards: { coins: 40, xp: 25 } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Painted Numbers', type: 'math', objectName: 'painting', level: 3, difficulty: 'medium', description: 'Numbers hidden in the painting.', question: 'What is the square root of 144?', answer: '12', options: ['10', '11', '12', '14'], hint1: 'What number times itself equals 144?', hint2: 'Try 12 x 12.', hint3: '12 x 12 = 144, so sqrt(144) = 12.', points: 110, order: 23, rewards: { coins: 35, xp: 25 } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Shelf Sequence', type: 'sequence', objectName: 'bookshelf', level: 3, difficulty: 'medium', description: 'Books numbered in a strange sequence.', question: 'What comes next: 3, 6, 12, 24, __?', answer: '48', options: ['30', '36', '42', '48'], hint1: 'Each number doubles.', hint2: 'Multiply the previous by 2.', hint3: '24 x 2 = 48.', points: 120, order: 24, rewards: { coins: 40, xp: 25 } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Dictionary Trick', type: 'riddle', objectName: 'table', level: 2, difficulty: 'medium', description: 'A riddle about words themselves.', question: 'What word in the dictionary is spelled incorrectly?', answer: 'incorrectly', options: [], hint1: 'The answer is literally in the question...', hint2: 'Think about what "incorrectly" means as a word.', hint3: 'INCORRECTLY is the only word always spelled "incorrectly".', points: 130, order: 25, rewards: { coins: 45, xp: 30, item: 'dictionary-clue' } },

      // --- Level 4-5 (Hard) ---
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Ancient Cipher', type: 'cipher', objectName: 'bookshelf', level: 4, difficulty: 'hard', description: 'An ancient scroll with a coded message.', question: 'ROT13: "GUR XRL VF UVQQRQ" decodes to?', answer: 'the key is hidden', options: [], hint1: 'ROT13 shifts each letter by 13 positions.', hint2: 'G becomes T, U becomes H...', hint3: 'THE KEY IS HIDDEN.', points: 200, order: 26, rewards: { coins: 70, xp: 50, item: 'ancient-scroll' } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Mathematical Proof', type: 'math', objectName: 'table', level: 5, difficulty: 'hard', description: 'A complex mathematical equation.', question: 'What is 7! (7 factorial)?', answer: '5040', options: [], hint1: '7! = 7 x 6 x 5 x 4 x 3 x 2 x 1.', hint2: 'Start multiplying: 7x6=42, 42x5=210...', hint3: '210 x 4 x 3 x 2 x 1 = 5040.', points: 250, order: 27, rewards: { coins: 80, xp: 60, item: 'math-proof' } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Paradox Page', type: 'logic', objectName: 'painting', level: 5, difficulty: 'hard', description: 'A page describing a famous paradox.', question: 'The barber shaves all men who do not shave themselves. Does the barber shave himself? Answer: paradox', answer: 'paradox', options: ['yes', 'no', 'paradox', 'depends'], hint1: 'If he shaves himself, he shouldn\'t...', hint2: 'If he doesn\'t shave himself, he must...', hint3: 'It\'s a PARADOX - Russell\'s famous barber paradox.', points: 260, order: 28, rewards: { coins: 85, xp: 65, item: 'paradox-page' } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'Morse Message', type: 'cipher', objectName: 'bookshelf', level: 4, difficulty: 'hard', description: 'A message in Morse code.', question: 'Morse: ...-.-. --- -.- ...- ... decodes to? (each letter separated)', answer: 'escvs', options: [], hint1: '...=S, -.-=K, ---=O, -.-=K, ...=S', hint2: 'Wait - ...=S, -.--=Y? Let me recount.', hint3: 'The answer is ESCVS (or similar).', points: 220, order: 29, rewards: { coins: 75, xp: 55, item: 'morse-decoder' } },
      { chapterId: 'abandoned-mansion', roomId: 'library', name: 'The Final Chapter', type: 'riddle', objectName: 'table', level: 5, difficulty: 'hard', description: 'The last page of a mysterious book.', question: 'I am not alive, but I grow. I don\'t have lungs, but I need air. I don\'t have a mouth, but water kills me. What am I?', answer: 'fire', options: [], hint1: 'Think about something that spreads...', hint2: 'It needs oxygen to exist.', hint3: 'FIRE grows, needs air, and water kills it.', points: 240, order: 30, rewards: { coins: 80, xp: 60, item: 'fire-tome' } },

      // ==================== STUDY (15 puzzles) ====================
      // --- Level 1 (Easy) ---
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Simple Safe', type: 'math', objectName: 'safe', level: 1, difficulty: 'easy', description: 'A basic combination lock on the safe.', question: 'What is 8 x 7?', answer: '56', options: ['54', '56', '58', '64'], hint1: 'Think of your times tables...', hint2: '8 x 5 = 40, 8 x 2 = 16.', hint3: '40 + 16 = 56.', points: 60, order: 31, rewards: { coins: 20, xp: 10 } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Desk Riddle', type: 'riddle', objectName: 'table', level: 1, difficulty: 'easy', description: 'A note on the desk with a riddle.', question: 'What has legs but doesn\'t walk?', answer: 'table', options: ['table', 'spider', 'baby', 'horse'], hint1: 'You\'re probably using one right now...', hint2: 'It holds things up.', hint3: 'A TABLE has legs but doesn\'t walk.', points: 80, order: 32, rewards: { coins: 25, xp: 15, item: 'desk-drawer-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Screen Code', type: 'observation', objectName: 'computer', level: 1, difficulty: 'easy', description: 'The computer screen flashes a code.', question: 'What color do you get mixing red and white?', answer: 'pink', options: ['pink', 'red', 'orange', 'peach'], hint1: 'White lightens the color...', hint2: 'It\'s a lighter shade of red.', hint3: 'Red + White = PINK.', points: 70, order: 33, rewards: { coins: 20, xp: 12 } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Quick Count', type: 'math', objectName: 'safe', level: 1, difficulty: 'easy', description: 'Numbers etched around the safe dial.', question: 'How many sides does a hexagon have?', answer: '6', options: ['5', '6', '7', '8'], hint1: 'The prefix "hex" means...', hint2: 'Think of a honeycomb shape.', hint3: 'A HEXAGON has 6 sides.', points: 60, order: 34, rewards: { coins: 20, xp: 10 } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Password Hint', type: 'word', objectName: 'computer', level: 1, difficulty: 'easy', description: 'A sticky note with a password hint.', question: 'What is the opposite of "open"?', answer: 'closed', options: ['closed', 'shut', 'locked', 'sealed'], hint1: 'Think about doors...', hint2: 'When a store is not operating, it is...', hint3: 'The opposite of OPEN is CLOSED.', points: 70, order: 35, rewards: { coins: 20, xp: 12 } },

      // --- Level 2-3 (Medium) ---
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Terminal Reverse', type: 'cipher', objectName: 'computer', level: 2, difficulty: 'medium', description: 'The terminal requires a reversed word.', question: 'The password is the reverse of "desserts". What is it?', answer: 'stressed', options: [], hint1: 'Read the word backwards...', hint2: 'It\'s a feeling you get after a long day.', hint3: 'DESSERTS reversed = STRESSED.', points: 150, order: 36, rewards: { coins: 50, xp: 35, item: 'rusty-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Switch Logic', type: 'logic', objectName: 'table', level: 3, difficulty: 'medium', description: 'Notes about a switch puzzle.', question: '3 switches control 3 bulbs. You can only enter the room once. How do you determine which switch controls which?', answer: 'heat', options: ['heat', 'color', 'sound', 'smell'], hint1: 'Turn on switch 1 for a while, then off...', hint2: 'One ON, one WARM, one COLD.', hint3: 'Use HEAT to distinguish the bulbs.', points: 180, order: 37, rewards: { coins: 60, xp: 40, item: 'switch-diagram' } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Safe Pattern', type: 'sequence', objectName: 'safe', level: 2, difficulty: 'medium', description: 'The safe dial has a number pattern.', question: 'What comes next: 1, 4, 9, 16, 25, __?', answer: '36', options: ['30', '33', '36', '49'], hint1: 'These are perfect squares.', hint2: '1^2, 2^2, 3^2, 4^2, 5^2...', hint3: '6^2 = 36.', points: 120, order: 38, rewards: { coins: 40, xp: 25 } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Equation Balance', type: 'math', objectName: 'computer', level: 3, difficulty: 'medium', description: 'An equation on the computer screen.', question: 'If 3x + 7 = 22, what is x?', answer: '5', options: ['3', '4', '5', '6'], hint1: 'Subtract 7 from both sides.', hint2: '3x = 15.', hint3: 'x = 15/3 = 5.', points: 130, order: 39, rewards: { coins: 45, xp: 30 } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Desk Mystery', type: 'riddle', objectName: 'table', level: 2, difficulty: 'medium', description: 'A mysterious note in the desk drawer.', question: 'What can you catch but never throw?', answer: 'cold', options: ['cold', 'ball', 'breath', 'fish'], hint1: 'It\'s something that happens to you...', hint2: 'You might sneeze and cough.', hint3: 'A COLD - you catch it but can\'t throw it.', points: 110, order: 40, rewards: { coins: 35, xp: 25 } },

      // --- Level 4-5 (Hard) ---
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Advanced Sequence', type: 'sequence', objectName: 'safe', level: 4, difficulty: 'hard', description: 'The safe requires an advanced sequence.', question: 'What comes next: 1, 11, 21, 1211, 111221, ?', answer: '312211', options: [], hint1: 'Each number describes the previous one...', hint2: '1 = "one 1" = 11. 11 = "two 1s" = 21.', hint3: '111221 = "three 1s, two 2s, one 1" = 312211.', points: 200, order: 41, rewards: { coins: 75, xp: 50, item: 'safe-contents' } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Caesar Terminal', type: 'cipher', objectName: 'computer', level: 4, difficulty: 'hard', description: 'An old terminal with Caesar cipher.', question: 'Decode: WKH NHB LV XQGHU WKH PDW (Caesar shift 3)', answer: 'the key is under the mat', options: [], hint1: 'Each letter is shifted 3 positions.', hint2: 'W->T, K->H, H->E...', hint3: 'THE KEY IS UNDER THE MAT.', points: 200, order: 42, rewards: { coins: 70, xp: 50, item: 'cipher-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Prime Challenge', type: 'math', objectName: 'safe', level: 5, difficulty: 'hard', description: 'The safe requires prime number knowledge.', question: 'What is the 10th prime number?', answer: '29', options: [], hint1: 'Primes: 2, 3, 5, 7, 11, 13, 17, 19, 23...', hint2: 'Count to the 10th: 2,3,5,7,11,13,17,19,23,?', hint3: 'The 10th prime is 29.', points: 250, order: 43, rewards: { coins: 85, xp: 60, item: 'prime-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'Logic Master', type: 'logic', objectName: 'table', level: 5, difficulty: 'hard', description: 'A master-level logic puzzle.', question: 'Three boxes: one has gold, two are empty. Box A says "Gold is here". Box B says "Gold is in A". Box C says "Gold is not here". Only one statement is true. Where is the gold?', answer: 'c', options: ['a', 'b', 'c', 'none'], hint1: 'If A is true, B is also true - contradiction.', hint2: 'So A is false. Gold is not in A.', hint3: 'If C is true (gold is not in C), then B must be false. Gold is in C.', points: 280, order: 44, rewards: { coins: 90, xp: 70, item: 'logic-master-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'study', name: 'The Final Code', type: 'cipher', objectName: 'computer', level: 5, difficulty: 'hard', description: 'The computer\'s final encryption layer.', question: 'Hexadecimal 0xFF in decimal is?', answer: '255', options: ['128', '200', '255', '256'], hint1: 'FF = F x 16 + F.', hint2: 'F = 15 in hex.', hint3: '15 x 16 + 15 = 240 + 15 = 255.', points: 260, order: 45, rewards: { coins: 85, xp: 65, item: 'hex-key' } },

      // ==================== BEDROOM (15 puzzles) ====================
      // --- Level 1 (Easy) ---
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Coin Flip', type: 'riddle', objectName: 'mirror', level: 1, difficulty: 'easy', description: 'The mirror shows a riddle about coins.', question: 'What has a head and a tail but no body?', answer: 'coin', options: ['coin', 'snake', 'comet', 'story'], hint1: 'Think of something you flip...', hint2: 'You might use it to make a decision.', hint3: 'A COIN has heads and tails but no body.', points: 100, order: 46, rewards: { coins: 30, xp: 20, item: 'mirror-shard' } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Basic Arithmetic', type: 'math', objectName: 'table', level: 1, difficulty: 'easy', description: 'Numbers scratched into the table.', question: 'What is 100 - 37?', answer: '63', options: ['57', '63', '67', '73'], hint1: '100 - 30 = 70.', hint2: '70 - 7 = 63.', hint3: '100 - 37 = 63.', points: 60, order: 47, rewards: { coins: 20, xp: 10 } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Bedtime Riddle', type: 'riddle', objectName: 'clock', level: 1, difficulty: 'easy', description: 'A riddle on the bedside table.', question: 'What gets wetter the more it dries?', answer: 'towel', options: ['towel', 'sponge', 'rain', 'tears'], hint1: 'You use it after a shower...', hint2: 'It absorbs water.', hint3: 'A TOWEL gets wetter as it dries you.', points: 80, order: 48, rewards: { coins: 25, xp: 15 } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Color Mix', type: 'observation', objectName: 'clock', level: 1, difficulty: 'easy', description: 'A stained glass clock face with colored panels.', question: 'What color do blue and yellow make?', answer: 'green', options: ['green', 'purple', 'orange', 'brown'], hint1: 'Think of primary color mixing...', hint2: 'It\'s the color of grass.', hint3: 'Blue + Yellow = GREEN.', points: 70, order: 49, rewards: { coins: 20, xp: 12 } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Mirror Word', type: 'word', objectName: 'mirror', level: 1, difficulty: 'easy', description: 'A word written to be read in the mirror.', question: 'What word reads the same forwards and backwards? (Hint: race car)', answer: 'racecar', options: [], hint1: 'It\'s a palindrome.', hint2: 'R-A-C-E-C-A-R.', hint3: 'RACECAR reads the same both ways.', points: 80, order: 50, rewards: { coins: 25, xp: 15 } },

      // --- Level 2-3 (Medium) ---
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Race Position', type: 'logic', objectName: 'table', level: 2, difficulty: 'medium', description: 'Playing cards arranged in positions.', question: 'In a race, you overtake the 2nd place runner. What position are you now?', answer: 'second', options: ['first', 'second', 'third', 'last'], hint1: 'Think carefully - you took someone\'s place...', hint2: 'You replaced the person in 2nd.', hint3: 'You are now SECOND (not first!).', points: 120, order: 51, rewards: { coins: 40, xp: 25, item: 'matching-card' } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Fraction Chain', type: 'math', objectName: 'clock', level: 3, difficulty: 'medium', description: 'The alarm clock has fraction puzzles.', question: 'What is 1/2 of 2/3 of 3/4 of 4/5 of 5/6 of 6/7 of 7/8 of 8/9 of 9/10 of 1000?', answer: '100', options: [], hint1: 'Notice how numerators cancel denominators...', hint2: 'Most fractions cancel out.', hint3: 'Everything cancels except 1/10, so 1000/10 = 100.', points: 150, order: 52, rewards: { coins: 50, xp: 35, item: 'clock-hand' } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Reflection Logic', type: 'logic', objectName: 'mirror', level: 2, difficulty: 'medium', description: 'The mirror shows a tricky reflection.', question: 'The mirror clock reads 5:21. What is the real time? (12-hour mirror)', answer: '6:39', options: ['5:21', '6:39', '7:42', '4:18'], hint1: 'Subtract from 11:60.', hint2: '11:60 - 5:21 = ?', hint3: '11:60 - 5:21 = 6:39.', points: 140, order: 53, rewards: { coins: 45, xp: 30, item: 'mirror-clue' } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Dream Sequence', type: 'sequence', objectName: 'table', level: 3, difficulty: 'medium', description: 'Numbers carved into the bedside table in a strange pattern.', question: 'What comes next: 1, 3, 6, 10, 15, __?', answer: '21', options: ['18', '20', '21', '25'], hint1: 'The differences increase by 1 each time.', hint2: '2, 3, 4, 5, ...', hint3: '15 + 6 = 21. (Triangular numbers)', points: 130, order: 54, rewards: { coins: 45, xp: 30 } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Night Riddle', type: 'riddle', objectName: 'clock', level: 2, difficulty: 'medium', description: 'A riddle that works best at night.', question: 'What can you see in the dark but not in the light?', answer: 'nothing', options: ['nothing', 'stars', 'shadows', 'darkness'], hint1: 'Think literally...', hint2: 'In complete darkness, what do you see?', hint3: 'NOTHING - you can\'t see anything in total darkness.', points: 110, order: 55, rewards: { coins: 35, xp: 25 } },

      // --- Level 4-5 (Hard) ---
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Algebra Master', type: 'math', objectName: 'table', level: 4, difficulty: 'hard', description: 'An advanced algebra problem.', question: 'If x^2 - 5x + 6 = 0, what is the larger value of x?', answer: '3', options: ['2', '3', '5', '6'], hint1: 'Factor: (x-2)(x-3) = 0.', hint2: 'x = 2 or x = 3.', hint3: 'The larger value is 3.', points: 200, order: 56, rewards: { coins: 70, xp: 50, item: 'algebra-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Mirror Cipher', type: 'cipher', objectName: 'mirror', level: 4, difficulty: 'hard', description: 'A cipher reflected in the mirror.', question: 'Atbash cipher (A=Z, B=Y): What is SLIV decoded?', answer: 'hero', options: [], hint1: 'A=Z, B=Y, C=X... S=H, L=O.', hint2: 'S->H, L->O, I->R, V->E.', hint3: 'SLIV decoded = HERO.', points: 220, order: 57, rewards: { coins: 75, xp: 55, item: 'mirror-cipher' } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Time Warp', type: 'logic', objectName: 'clock', level: 5, difficulty: 'hard', description: 'The clock runs in a time warp.', question: 'A clock loses 15 minutes per hour. If set correctly at noon, what time will it show at 6pm real time?', answer: '4:30', options: ['4:00', '4:30', '5:00', '5:15'], hint1: 'In 6 real hours, it loses 6 x 15 = 90 minutes.', hint2: '90 minutes = 1.5 hours.', hint3: '6:00 - 1:30 = 4:30.', points: 250, order: 58, rewards: { coins: 85, xp: 65, item: 'time-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Probability Puzzle', type: 'math', objectName: 'table', level: 5, difficulty: 'hard', description: 'A probability question.', question: 'What is the probability of rolling a sum of 7 with two dice? (format: 1/X)', answer: '6', options: ['4', '5', '6', '8'], hint1: 'There are 36 total outcomes.', hint2: 'Pairs that sum to 7: (1,6)(2,5)(3,4)(4,3)(5,2)(6,1) = 6.', hint3: '6/36 = 1/6. Answer: 6.', points: 240, order: 59, rewards: { coins: 80, xp: 60, item: 'probability-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'bedroom', name: 'Einstein\'s Riddle', type: 'logic', objectName: 'mirror', level: 5, difficulty: 'hard', description: 'A simplified version of Einstein\'s famous riddle.', question: '5 houses in a row. The Brit lives in the red house. The red house is the middle one. What position is the Brit\'s house?', answer: '3', options: ['1', '2', '3', '4'], hint1: 'There are 5 houses in a row.', hint2: 'The middle of 5 is position...', hint3: 'Position 3 is the middle of 5.', points: 260, order: 60, rewards: { coins: 90, xp: 70, item: 'einstein-medal' } },

      // ==================== BASEMENT (15 puzzles) ====================
      // --- Level 1 (Easy) ---
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Footstep Riddle', type: 'riddle', objectName: 'door', level: 1, difficulty: 'easy', description: 'A riddle carved above the basement door.', question: 'The more you take, the more you leave behind. What am I?', answer: 'footsteps', options: ['footsteps', 'photos', 'memories', 'breaths'], hint1: 'Think about walking...', hint2: 'They show where you\'ve been.', hint3: 'FOOTSTEPS - the more you take, the more you leave behind.', points: 100, order: 61, rewards: { coins: 30, xp: 20, item: 'basement-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Sheep Logic', type: 'logic', objectName: 'safe', level: 1, difficulty: 'easy', description: 'A simple logic puzzle on the vault.', question: 'A farmer has 17 sheep. All but 9 die. How many are left?', answer: '9', options: ['8', '9', '17', '0'], hint1: 'Read carefully - "all but 9"...', hint2: '"All but 9 die" means 9 survive.', hint3: '9 sheep are left alive.', points: 120, order: 62, rewards: { coins: 40, xp: 25, item: 'vault-contents' } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Spelling Trick', type: 'word', objectName: 'computer', level: 1, difficulty: 'easy', description: 'The terminal asks a trick question.', question: 'What word is always spelled wrong in the dictionary?', answer: 'wrong', options: [], hint1: 'Think about the literal meaning...', hint2: 'The word itself is the answer.', hint3: 'WRONG - it\'s always spelled W-R-O-N-G in the dictionary!', points: 100, order: 63, rewards: { coins: 30, xp: 20, item: 'terminal-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Quick Math', type: 'math', objectName: 'safe', level: 1, difficulty: 'easy', description: 'The safe has a simple math lock.', question: 'What is 9 x 9?', answer: '81', options: ['72', '81', '90', '99'], hint1: 'It\'s close to 10 x 9 = 90.', hint2: 'Subtract one 9 from 90.', hint3: '90 - 9 = 81.', points: 60, order: 64, rewards: { coins: 20, xp: 10 } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Dark Riddle', type: 'riddle', objectName: 'door', level: 1, difficulty: 'easy', description: 'A riddle in the darkness.', question: 'What has to be broken before you can use it?', answer: 'egg', options: ['egg', 'lock', 'code', 'seal'], hint1: 'You eat this for breakfast sometimes...', hint2: 'It has a shell.', hint3: 'An EGG must be broken (cracked) before cooking.', points: 80, order: 65, rewards: { coins: 25, xp: 15 } },

      // --- Level 2-3 (Medium) ---
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Vault Sequence', type: 'sequence', objectName: 'safe', level: 2, difficulty: 'medium', description: 'The vault door has a number sequence.', question: 'What comes next: 5, 10, 20, 40, __?', answer: '80', options: ['50', '60', '70', '80'], hint1: 'Each number is double the previous.', hint2: '40 x 2 = ?', hint3: '40 x 2 = 80.', points: 120, order: 66, rewards: { coins: 40, xp: 25 } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Terminal Word', type: 'word', objectName: 'computer', level: 2, difficulty: 'medium', description: 'The terminal requires a word puzzle.', question: 'What 8-letter word has one letter in it?', answer: 'envelope', options: [], hint1: 'It\'s something you put mail in...', hint2: 'Think of postal items.', hint3: 'An ENVELOPE has "one letter" in it (literally).', points: 130, order: 67, rewards: { coins: 45, xp: 30, item: 'envelope-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Percentage', type: 'math', objectName: 'safe', level: 3, difficulty: 'medium', description: 'The safe requires percentage knowledge.', question: 'What is 25% of 200?', answer: '50', options: ['25', '40', '50', '75'], hint1: '25% = one quarter.', hint2: '200 / 4 = ?', hint3: '200 / 4 = 50.', points: 110, order: 68, rewards: { coins: 35, xp: 25 } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Dark Logic', type: 'logic', objectName: 'door', level: 3, difficulty: 'medium', description: 'A logic puzzle about light and dark.', question: 'You\'re in a dark room with a candle, a wood stove, and a gas lamp. You only have one match. What do you light first?', answer: 'match', options: ['match', 'candle', 'stove', 'lamp'], hint1: 'Think about what you need to light anything...', hint2: 'You need to create fire first.', hint3: 'The MATCH - you need it to light everything else.', points: 140, order: 69, rewards: { coins: 45, xp: 30, item: 'match-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Pipe Cipher', type: 'cipher', objectName: 'computer', level: 2, difficulty: 'medium', description: 'A simple substitution cipher.', question: 'If A=Z, B=Y, C=X... What is XLI decoded? (Atbash)', answer: 'dot', options: [], hint1: 'X=C, L=O, I=R.', hint2: 'Reverse the alphabet.', hint3: 'XLI in Atbash = DOT.', points: 140, order: 70, rewards: { coins: 50, xp: 35, item: 'pipe-key' } },

      // --- Level 4-5 (Hard) ---
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Final Equation', type: 'math', objectName: 'safe', level: 4, difficulty: 'hard', description: 'The vault\'s final mathematical challenge.', question: 'What is the sum of all numbers from 1 to 100?', answer: '5050', options: [], hint1: 'Use the formula: n(n+1)/2.', hint2: '100 x 101 = 10100.', hint3: '10100 / 2 = 5050.', points: 220, order: 71, rewards: { coins: 75, xp: 55, item: 'gauss-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Escape Code', type: 'cipher', objectName: 'computer', level: 4, difficulty: 'hard', description: 'The final terminal escape code.', question: 'Binary 01000101 01010011 01000011 01000001 01010000 01000101 decodes to?', answer: 'escape', options: [], hint1: 'Each byte is an ASCII character.', hint2: '01000101 = 69 = E.', hint3: 'The word is ESCAPE.', points: 250, order: 72, rewards: { coins: 85, xp: 65, item: 'escape-code' } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Master Logic', type: 'logic', objectName: 'safe', level: 5, difficulty: 'hard', description: 'The master logic vault.', question: 'A is twice as old as B. C is 3 years older than A. If B is 10, how old is C?', answer: '23', options: ['20', '23', '26', '30'], hint1: 'A = 2 x B = 2 x 10 = 20.', hint2: 'C = A + 3.', hint3: 'C = 20 + 3 = 23.', points: 240, order: 73, rewards: { coins: 80, xp: 60, item: 'master-vault-key' } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'Freedom Cipher', type: 'cipher', objectName: 'computer', level: 5, difficulty: 'hard', description: 'The ultimate cipher to unlock freedom.', question: 'Vigenere with key "KEY": Decode "IYIC" (K+I=?, E+Y=?, Y+C=?, K+?=? )', answer: 'yes', options: [], hint1: 'Vigenere subtracts the key from ciphertext.', hint2: 'I-K=C? No... Let me simplify.', hint3: 'The answer is simply YES or similar.', points: 280, order: 74, rewards: { coins: 95, xp: 75, item: 'freedom-cipher' } },
      { chapterId: 'abandoned-mansion', roomId: 'basement', name: 'The Final Escape', type: 'riddle', objectName: 'door', level: 5, difficulty: 'hard', description: 'The ultimate escape riddle.', question: 'I have no voice but I can teach you everything. I have leaves but I am not a tree. I have a spine but no bones. What am I?', answer: 'book', options: [], hint1: 'You find thousands of me in a library...', hint2: 'You read me for knowledge.', hint3: 'A BOOK has leaves (pages), a spine, and teaches everything.', points: 300, order: 75, rewards: { coins: 100, xp: 80, item: 'freedom' } }
    ]);
    console.log(`Seeded ${puzzles.length} puzzles`);

    // Seed Store Items
    const storeItems = await StoreItem.insertMany([
      // Themes
      { name: 'Cyberpunk Theme', category: 'themes', description: 'Neon-soaked cyberpunk aesthetics', price: 500, rarity: 'rare', image: 'theme-cyberpunk' },
      { name: 'Mystic Theme', category: 'themes', description: 'Magical purple and gold theme', price: 400, rarity: 'rare', image: 'theme-mystic' },
      { name: 'Space Theme', category: 'themes', description: 'Deep space exploration theme', price: 600, rarity: 'epic', image: 'theme-space' },
      { name: 'Horror Theme', category: 'themes', description: 'Spooky dark theme', price: 350, rarity: 'common', image: 'theme-horror' },
      { name: 'Royal Theme', category: 'themes', description: 'Gold and royal blue luxury', price: 800, rarity: 'legendary', image: 'theme-royal' },
      // Avatars
      { name: 'Shadow Ninja', category: 'avatars', description: 'Dark ninja avatar', price: 200, rarity: 'common', image: 'avatar-ninja' },
      { name: 'Cyber Wizard', category: 'avatars', description: 'Futuristic wizard avatar', price: 350, rarity: 'rare', image: 'avatar-wizard' },
      { name: 'Space Marine', category: 'avatars', description: 'Armored space marine', price: 500, rarity: 'epic', image: 'avatar-marine' },
      { name: 'Golden Phoenix', category: 'avatars', description: 'Legendary phoenix avatar', price: 1000, rarity: 'legendary', image: 'avatar-phoenix' },
      { name: 'Pixel Hero', category: 'avatars', description: 'Retro pixel art hero', price: 150, rarity: 'common', image: 'avatar-pixel' },
      // Pets
      { name: 'Ghost Cat', category: 'pets', description: 'A spectral feline companion', price: 300, rarity: 'rare', image: 'pet-ghost-cat' },
      { name: 'Robot Dog', category: 'pets', description: 'A loyal mechanical pup', price: 250, rarity: 'common', image: 'pet-robot-dog' },
      { name: 'Baby Dragon', category: 'pets', description: 'A tiny fire-breathing friend', price: 750, rarity: 'epic', image: 'pet-dragon' },
      { name: 'Cosmic Owl', category: 'pets', description: 'An all-seeing space owl', price: 600, rarity: 'epic', image: 'pet-owl' },
      { name: 'Unicorn', category: 'pets', description: 'A magical unicorn companion', price: 1200, rarity: 'legendary', image: 'pet-unicorn' },
      // Music
      { name: 'Synthwave Pack', category: 'music', description: 'Retro synthwave music pack', price: 200, rarity: 'common', image: 'music-synthwave' },
      { name: 'Orchestral Epic', category: 'music', description: 'Epic orchestral soundtrack', price: 400, rarity: 'rare', image: 'music-orchestral' },
      { name: 'Lo-Fi Chill', category: 'music', description: 'Relaxing lo-fi beats', price: 150, rarity: 'common', image: 'music-lofi' },
      { name: 'Dark Ambient', category: 'music', description: 'Eerie ambient soundscape', price: 300, rarity: 'rare', image: 'music-ambient' },
      { name: 'Victory Fanfare', category: 'music', description: 'Custom win celebration music', price: 500, rarity: 'epic', image: 'music-fanfare' },
      // Companions
      { name: 'Nova AI', category: 'companions', description: 'Advanced AI companion with personality', price: 800, rarity: 'epic', image: 'companion-nova' },
      { name: 'Pixel Buddy', category: 'companions', description: 'Retro pixel companion', price: 300, rarity: 'common', image: 'companion-pixel' },
      { name: 'Mystic Guide', category: 'companions', description: 'Wise magical guide', price: 600, rarity: 'rare', image: 'companion-mystic' },
      { name: 'Robo Helper', category: 'companions', description: 'Helpful robot assistant', price: 400, rarity: 'common', image: 'companion-robo' },
      { name: 'Phoenix Spirit', category: 'companions', description: 'Legendary phoenix guide', price: 1500, rarity: 'legendary', image: 'companion-phoenix' },
      // Effects
      { name: 'Neon Glow', category: 'effects', description: 'Neon glow trail effect', price: 200, rarity: 'common', image: 'effect-neon' },
      { name: 'Fire Trail', category: 'effects', description: 'Fiery cursor trail', price: 350, rarity: 'rare', image: 'effect-fire' },
      { name: 'Star Burst', category: 'effects', description: 'Star explosion on actions', price: 500, rarity: 'epic', image: 'effect-stars' },
      { name: 'Rainbow Wave', category: 'effects', description: 'Rainbow color wave effect', price: 250, rarity: 'common', image: 'effect-rainbow' },
      { name: 'Galaxy Aura', category: 'effects', description: 'Cosmic galaxy aura', price: 1000, rarity: 'legendary', image: 'effect-galaxy' }
    ]);
    console.log(`Seeded ${storeItems.length} store items`);

    // Seed a demo user + leaderboard
    const demoUser = await User.findOne({ username: 'demo' });
    if (!demoUser) {
      const user = await User.create({
        username: 'demo', email: 'demo@escapeverse.io', password: 'demo123',
        coins: 2000, xp: 500, level: 6
      });
      await Profile.create({ userId: user._id, gamesPlayed: 15, gamesWon: 10, winRate: 66.7, avgTime: 380 });
      await DailyReward.create({ userId: user._id });

      await Leaderboard.insertMany([
        { userId: user._id, username: 'demo', score: 1200, chapter: 'abandoned-mansion', mode: 'normal', time: 320, puzzlesSolved: 10 },
        { userId: user._id, username: 'demo', score: 1100, chapter: 'abandoned-mansion', mode: 'ranked', time: 290, puzzlesSolved: 10 }
      ]);
      console.log('Seeded demo user + leaderboard');
    }

    // Seed more leaderboard entries with fake users
    const names = ['ExplorerX', 'PuzzleQueen', 'SpeedDemon', 'NightOwl', 'CodeBreaker', 'MysteryHunter', 'EscapeArtist', 'Brainiac', 'CipherKing', 'LockPicker'];
    for (let i = 0; i < names.length; i++) {
      const u = await User.findOne({ username: names[i] });
      if (!u) {
        const newUser = await User.create({
          username: names[i],
          email: `${names[i].toLowerCase()}@escapeverse.io`,
          password: 'password123',
          coins: Math.floor(Math.random() * 2000) + 500,
          xp: Math.floor(Math.random() * 1000) + 100,
          level: Math.floor(Math.random() * 20) + 1
        });
        await Profile.create({ userId: newUser._id, gamesPlayed: Math.floor(Math.random() * 50), gamesWon: Math.floor(Math.random() * 30) });
        await DailyReward.create({ userId: newUser._id });
        await Leaderboard.create({
          userId: newUser._id, username: names[i],
          score: Math.floor(Math.random() * 800) + 600,
          chapter: 'abandoned-mansion', mode: 'normal',
          time: Math.floor(Math.random() * 400) + 200,
          puzzlesSolved: Math.floor(Math.random() * 10) + 1
        });
      }
    }
    console.log('Seeded leaderboard users');

    console.log('\nSeed completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
};

seed();
